/*
 * This file is generated by jOOQ.
 */
package org.opm.busybeaver.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.opm.busybeaver.jooq.tables.Beaverusers;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BeaverusersRecord extends UpdatableRecordImpl<BeaverusersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.beaverusers.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.beaverusers.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.beaverusers.email</code>.
     */
    public void setEmail(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.beaverusers.email</code>.
     */
    public String getEmail() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.beaverusers.username</code>.
     */
    public void setUsername(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.beaverusers.username</code>.
     */
    public String getUsername() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.beaverusers.firebase_id</code>.
     */
    public void setFirebaseId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.beaverusers.firebase_id</code>.
     */
    public String getFirebaseId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.beaverusers.role</code>.
     */
    public void setRole(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.beaverusers.role</code>.
     */
    public String getRole() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BeaverusersRecord
     */
    public BeaverusersRecord() {
        super(Beaverusers.BEAVERUSERS);
    }

    /**
     * Create a detached, initialised BeaverusersRecord
     */
    public BeaverusersRecord(Integer userId, String email, String username, String firebaseId, String role) {
        super(Beaverusers.BEAVERUSERS);

        setUserId(userId);
        setEmail(email);
        setUsername(username);
        setFirebaseId(firebaseId);
        setRole(role);
        resetChangedOnNotNull();
    }
}
