/*
 * This file is generated by jOOQ.
 */
package org.opm.busybeaver.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.opm.busybeaver.jooq.tables.Columns;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ColumnsRecord extends UpdatableRecordImpl<ColumnsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.columns.column_id</code>.
     */
    public void setColumnId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.columns.column_id</code>.
     */
    public Integer getColumnId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.columns.project_id</code>.
     */
    public void setProjectId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.columns.project_id</code>.
     */
    public Integer getProjectId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.columns.column_title</code>.
     */
    public void setColumnTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.columns.column_title</code>.
     */
    public String getColumnTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.columns.column_index</code>.
     */
    public void setColumnIndex(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.columns.column_index</code>.
     */
    public Short getColumnIndex() {
        return (Short) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ColumnsRecord
     */
    public ColumnsRecord() {
        super(Columns.COLUMNS);
    }

    /**
     * Create a detached, initialised ColumnsRecord
     */
    public ColumnsRecord(Integer columnId, Integer projectId, String columnTitle, Short columnIndex) {
        super(Columns.COLUMNS);

        setColumnId(columnId);
        setProjectId(projectId);
        setColumnTitle(columnTitle);
        setColumnIndex(columnIndex);
        resetChangedOnNotNull();
    }
}
