/*
 * This file is generated by jOOQ.
 */
package org.opm.busybeaver.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.opm.busybeaver.jooq.tables.Projectusers;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProjectusersRecord extends UpdatableRecordImpl<ProjectusersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.projectusers.user_project_id</code>.
     */
    public void setUserProjectId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.projectusers.user_project_id</code>.
     */
    public Integer getUserProjectId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.projectusers.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.projectusers.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.projectusers.project_id</code>.
     */
    public void setProjectId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.projectusers.project_id</code>.
     */
    public Integer getProjectId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.projectusers.user_project_role</code>.
     */
    public void setUserProjectRole(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.projectusers.user_project_role</code>.
     */
    public String getUserProjectRole() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProjectusersRecord
     */
    public ProjectusersRecord() {
        super(Projectusers.PROJECTUSERS);
    }

    /**
     * Create a detached, initialised ProjectusersRecord
     */
    public ProjectusersRecord(Integer userProjectId, Integer userId, Integer projectId, String userProjectRole) {
        super(Projectusers.PROJECTUSERS);

        setUserProjectId(userProjectId);
        setUserId(userId);
        setProjectId(projectId);
        setUserProjectRole(userProjectRole);
        resetChangedOnNotNull();
    }
}
