/*
 * This file is generated by jOOQ.
 */
package org.opm.busybeaver.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.opm.busybeaver.jooq.tables.Teamusers;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TeamusersRecord extends UpdatableRecordImpl<TeamusersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.teamusers.user_team_id</code>.
     */
    public void setUserTeamId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.teamusers.user_team_id</code>.
     */
    public Integer getUserTeamId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.teamusers.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.teamusers.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.teamusers.team_id</code>.
     */
    public void setTeamId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.teamusers.team_id</code>.
     */
    public Integer getTeamId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.teamusers.user_team_role</code>.
     */
    public void setUserTeamRole(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.teamusers.user_team_role</code>.
     */
    public String getUserTeamRole() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TeamusersRecord
     */
    public TeamusersRecord() {
        super(Teamusers.TEAMUSERS);
    }

    /**
     * Create a detached, initialised TeamusersRecord
     */
    public TeamusersRecord(Integer userTeamId, Integer userId, Integer teamId, String userTeamRole) {
        super(Teamusers.TEAMUSERS);

        setUserTeamId(userTeamId);
        setUserId(userId);
        setTeamId(teamId);
        setUserTeamRole(userTeamRole);
        resetChangedOnNotNull();
    }
}
