/*
 * This file is generated by jOOQ.
 */
package org.opm.busybeaver.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.opm.busybeaver.jooq.tables.Teams;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TeamsRecord extends UpdatableRecordImpl<TeamsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.teams.team_id</code>.
     */
    public void setTeamId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.teams.team_id</code>.
     */
    public Integer getTeamId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.teams.team_name</code>.
     */
    public void setTeamName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.teams.team_name</code>.
     */
    public String getTeamName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.teams.team_creator</code>.
     */
    public void setTeamCreator(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.teams.team_creator</code>.
     */
    public Integer getTeamCreator() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TeamsRecord
     */
    public TeamsRecord() {
        super(Teams.TEAMS);
    }

    /**
     * Create a detached, initialised TeamsRecord
     */
    public TeamsRecord(Integer teamId, String teamName, Integer teamCreator) {
        super(Teams.TEAMS);

        setTeamId(teamId);
        setTeamName(teamName);
        setTeamCreator(teamCreator);
        resetChangedOnNotNull();
    }
}
