/*
 * This file is generated by jOOQ.
 */
package org.opm.busybeaver.jooq;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.opm.busybeaver.jooq.tables.Beaverusers;
import org.opm.busybeaver.jooq.tables.Columns;
import org.opm.busybeaver.jooq.tables.Comments;
import org.opm.busybeaver.jooq.tables.Projects;
import org.opm.busybeaver.jooq.tables.Projectusers;
import org.opm.busybeaver.jooq.tables.Sprints;
import org.opm.busybeaver.jooq.tables.Tasks;
import org.opm.busybeaver.jooq.tables.Teams;
import org.opm.busybeaver.jooq.tables.Teamusers;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.beaverusers</code>.
     */
    public final Beaverusers BEAVERUSERS = Beaverusers.BEAVERUSERS;

    /**
     * The table <code>public.columns</code>.
     */
    public final Columns COLUMNS = Columns.COLUMNS;

    /**
     * The table <code>public.comments</code>.
     */
    public final Comments COMMENTS = Comments.COMMENTS;

    /**
     * The table <code>public.projects</code>.
     */
    public final Projects PROJECTS = Projects.PROJECTS;

    /**
     * The table <code>public.projectusers</code>.
     */
    public final Projectusers PROJECTUSERS = Projectusers.PROJECTUSERS;

    /**
     * The table <code>public.sprints</code>.
     */
    public final Sprints SPRINTS = Sprints.SPRINTS;

    /**
     * The table <code>public.tasks</code>.
     */
    public final Tasks TASKS = Tasks.TASKS;

    /**
     * The table <code>public.teams</code>.
     */
    public final Teams TEAMS = Teams.TEAMS;

    /**
     * The table <code>public.teamusers</code>.
     */
    public final Teamusers TEAMUSERS = Teamusers.TEAMUSERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Beaverusers.BEAVERUSERS,
            Columns.COLUMNS,
            Comments.COMMENTS,
            Projects.PROJECTS,
            Projectusers.PROJECTUSERS,
            Sprints.SPRINTS,
            Tasks.TASKS,
            Teams.TEAMS,
            Teamusers.TEAMUSERS
        );
    }
}
