/*
 * This file is generated by jOOQ.
 */
package org.opm.busybeaver.jooq;


import org.opm.busybeaver.jooq.tables.Beaverusers;
import org.opm.busybeaver.jooq.tables.Columns;
import org.opm.busybeaver.jooq.tables.Comments;
import org.opm.busybeaver.jooq.tables.Projects;
import org.opm.busybeaver.jooq.tables.Projectusers;
import org.opm.busybeaver.jooq.tables.Sprints;
import org.opm.busybeaver.jooq.tables.Tasks;
import org.opm.busybeaver.jooq.tables.Teams;
import org.opm.busybeaver.jooq.tables.Teamusers;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.beaverusers</code>.
     */
    public static final Beaverusers BEAVERUSERS = Beaverusers.BEAVERUSERS;

    /**
     * The table <code>public.columns</code>.
     */
    public static final Columns COLUMNS = Columns.COLUMNS;

    /**
     * The table <code>public.comments</code>.
     */
    public static final Comments COMMENTS = Comments.COMMENTS;

    /**
     * The table <code>public.projects</code>.
     */
    public static final Projects PROJECTS = Projects.PROJECTS;

    /**
     * The table <code>public.projectusers</code>.
     */
    public static final Projectusers PROJECTUSERS = Projectusers.PROJECTUSERS;

    /**
     * The table <code>public.sprints</code>.
     */
    public static final Sprints SPRINTS = Sprints.SPRINTS;

    /**
     * The table <code>public.tasks</code>.
     */
    public static final Tasks TASKS = Tasks.TASKS;

    /**
     * The table <code>public.teams</code>.
     */
    public static final Teams TEAMS = Teams.TEAMS;

    /**
     * The table <code>public.teamusers</code>.
     */
    public static final Teamusers TEAMUSERS = Teamusers.TEAMUSERS;
}
