/*
 * This file is generated by jOOQ.
 */
package org.opm.busybeaver.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.opm.busybeaver.jooq.Keys;
import org.opm.busybeaver.jooq.Public;
import org.opm.busybeaver.jooq.tables.Projectusers.ProjectusersPath;
import org.opm.busybeaver.jooq.tables.Tasks.TasksPath;
import org.opm.busybeaver.jooq.tables.records.CommentsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Comments extends TableImpl<CommentsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.comments</code>
     */
    public static final Comments COMMENTS = new Comments();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CommentsRecord> getRecordType() {
        return CommentsRecord.class;
    }

    /**
     * The column <code>public.comments.comment_id</code>.
     */
    public final TableField<CommentsRecord, Integer> COMMENT_ID = createField(DSL.name("comment_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.comments.user_id</code>.
     */
    public final TableField<CommentsRecord, Integer> USER_ID = createField(DSL.name("user_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.comments.task_id</code>.
     */
    public final TableField<CommentsRecord, Integer> TASK_ID = createField(DSL.name("task_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.comments.comment_created</code>.
     */
    public final TableField<CommentsRecord, LocalDateTime> COMMENT_CREATED = createField(DSL.name("comment_created"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.comments.comment_body</code>.
     */
    public final TableField<CommentsRecord, String> COMMENT_BODY = createField(DSL.name("comment_body"), SQLDataType.CLOB, this, "");

    private Comments(Name alias, Table<CommentsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Comments(Name alias, Table<CommentsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.comments</code> table reference
     */
    public Comments(String alias) {
        this(DSL.name(alias), COMMENTS);
    }

    /**
     * Create an aliased <code>public.comments</code> table reference
     */
    public Comments(Name alias) {
        this(alias, COMMENTS);
    }

    /**
     * Create a <code>public.comments</code> table reference
     */
    public Comments() {
        this(DSL.name("comments"), null);
    }

    public <O extends Record> Comments(Table<O> path, ForeignKey<O, CommentsRecord> childPath, InverseForeignKey<O, CommentsRecord> parentPath) {
        super(path, childPath, parentPath, COMMENTS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CommentsPath extends Comments implements Path<CommentsRecord> {
        public <O extends Record> CommentsPath(Table<O> path, ForeignKey<O, CommentsRecord> childPath, InverseForeignKey<O, CommentsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CommentsPath(Name alias, Table<CommentsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CommentsPath as(String alias) {
            return new CommentsPath(DSL.name(alias), this);
        }

        @Override
        public CommentsPath as(Name alias) {
            return new CommentsPath(alias, this);
        }

        @Override
        public CommentsPath as(Table<?> alias) {
            return new CommentsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<CommentsRecord, Integer> getIdentity() {
        return (Identity<CommentsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<CommentsRecord> getPrimaryKey() {
        return Keys.COMMENTS_PKEY;
    }

    @Override
    public List<ForeignKey<CommentsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.COMMENTS__COMMENTS_USER_ID_FKEY, Keys.COMMENTS__COMMENTS_TASK_ID_FKEY);
    }

    private transient ProjectusersPath _projectusers;

    /**
     * Get the implicit join path to the <code>public.projectusers</code> table.
     */
    public ProjectusersPath projectusers() {
        if (_projectusers == null)
            _projectusers = new ProjectusersPath(this, Keys.COMMENTS__COMMENTS_USER_ID_FKEY, null);

        return _projectusers;
    }

    private transient TasksPath _tasks;

    /**
     * Get the implicit join path to the <code>public.tasks</code> table.
     */
    public TasksPath tasks() {
        if (_tasks == null)
            _tasks = new TasksPath(this, Keys.COMMENTS__COMMENTS_TASK_ID_FKEY, null);

        return _tasks;
    }

    @Override
    public Comments as(String alias) {
        return new Comments(DSL.name(alias), this);
    }

    @Override
    public Comments as(Name alias) {
        return new Comments(alias, this);
    }

    @Override
    public Comments as(Table<?> alias) {
        return new Comments(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Comments rename(String name) {
        return new Comments(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Comments rename(Name name) {
        return new Comments(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Comments rename(Table<?> name) {
        return new Comments(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Comments where(Condition condition) {
        return new Comments(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Comments where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Comments where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Comments where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Comments where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Comments where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Comments where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Comments where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Comments whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Comments whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
