/*
 * This file is generated by jOOQ.
 */
package org.opm.busybeaver.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.opm.busybeaver.jooq.Keys;
import org.opm.busybeaver.jooq.Public;
import org.opm.busybeaver.jooq.tables.Beaverusers.BeaverusersPath;
import org.opm.busybeaver.jooq.tables.Projects.ProjectsPath;
import org.opm.busybeaver.jooq.tables.Teamusers.TeamusersPath;
import org.opm.busybeaver.jooq.tables.records.TeamsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Teams extends TableImpl<TeamsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.teams</code>
     */
    public static final Teams TEAMS = new Teams();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TeamsRecord> getRecordType() {
        return TeamsRecord.class;
    }

    /**
     * The column <code>public.teams.team_id</code>.
     */
    public final TableField<TeamsRecord, Integer> TEAM_ID = createField(DSL.name("team_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.teams.team_name</code>.
     */
    public final TableField<TeamsRecord, String> TEAM_NAME = createField(DSL.name("team_name"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.teams.team_creator</code>.
     */
    public final TableField<TeamsRecord, Integer> TEAM_CREATOR = createField(DSL.name("team_creator"), SQLDataType.INTEGER.nullable(false), this, "");

    private Teams(Name alias, Table<TeamsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Teams(Name alias, Table<TeamsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.teams</code> table reference
     */
    public Teams(String alias) {
        this(DSL.name(alias), TEAMS);
    }

    /**
     * Create an aliased <code>public.teams</code> table reference
     */
    public Teams(Name alias) {
        this(alias, TEAMS);
    }

    /**
     * Create a <code>public.teams</code> table reference
     */
    public Teams() {
        this(DSL.name("teams"), null);
    }

    public <O extends Record> Teams(Table<O> path, ForeignKey<O, TeamsRecord> childPath, InverseForeignKey<O, TeamsRecord> parentPath) {
        super(path, childPath, parentPath, TEAMS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TeamsPath extends Teams implements Path<TeamsRecord> {
        public <O extends Record> TeamsPath(Table<O> path, ForeignKey<O, TeamsRecord> childPath, InverseForeignKey<O, TeamsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TeamsPath(Name alias, Table<TeamsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TeamsPath as(String alias) {
            return new TeamsPath(DSL.name(alias), this);
        }

        @Override
        public TeamsPath as(Name alias) {
            return new TeamsPath(alias, this);
        }

        @Override
        public TeamsPath as(Table<?> alias) {
            return new TeamsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<TeamsRecord, Integer> getIdentity() {
        return (Identity<TeamsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<TeamsRecord> getPrimaryKey() {
        return Keys.TEAMS_PKEY;
    }

    @Override
    public List<UniqueKey<TeamsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UNIQUE_TEAM_PER_CREATOR);
    }

    @Override
    public List<ForeignKey<TeamsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.TEAMS__TEAMS_TEAM_CREATOR_FKEY);
    }

    private transient BeaverusersPath _beaverusers;

    /**
     * Get the implicit join path to the <code>public.beaverusers</code> table.
     */
    public BeaverusersPath beaverusers() {
        if (_beaverusers == null)
            _beaverusers = new BeaverusersPath(this, Keys.TEAMS__TEAMS_TEAM_CREATOR_FKEY, null);

        return _beaverusers;
    }

    private transient ProjectsPath _projects;

    /**
     * Get the implicit to-many join path to the <code>public.projects</code>
     * table
     */
    public ProjectsPath projects() {
        if (_projects == null)
            _projects = new ProjectsPath(this, null, Keys.PROJECTS__PROJECTS_TEAM_ID_FKEY.getInverseKey());

        return _projects;
    }

    private transient TeamusersPath _teamusers;

    /**
     * Get the implicit to-many join path to the <code>public.teamusers</code>
     * table
     */
    public TeamusersPath teamusers() {
        if (_teamusers == null)
            _teamusers = new TeamusersPath(this, null, Keys.TEAMUSERS__TEAMUSERS_TEAM_ID_FKEY.getInverseKey());

        return _teamusers;
    }

    @Override
    public Teams as(String alias) {
        return new Teams(DSL.name(alias), this);
    }

    @Override
    public Teams as(Name alias) {
        return new Teams(alias, this);
    }

    @Override
    public Teams as(Table<?> alias) {
        return new Teams(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Teams rename(String name) {
        return new Teams(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Teams rename(Name name) {
        return new Teams(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Teams rename(Table<?> name) {
        return new Teams(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Teams where(Condition condition) {
        return new Teams(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Teams where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Teams where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Teams where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Teams where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Teams where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Teams where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Teams where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Teams whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Teams whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
